### ISSUE TITLE
Not seeing any translations on page

### ISSUE THREAD

**Issue by jfmasciocco** [OiWorld/MindTheWord#104]
I've tried reinstalling Chrome, Yandex vs. Google Translate, rebooting chrome, none of the websites I visit have Spa
[MTW Screen Shot.docx](https://github.com/OiWorld/MindTheWord/files/193506/MTW.Screen.Shot.docx)
nish words

**Comment by Ceilican** [comment]
Hi! I have just uploaded a new version of the extension. A long-standing bug that caused the extension not to work for a few users has finally been fixed. Please try it again now. If you continue experiencing any difficulties, please let me know.

**Comment by jfmasciocco** [comment]
Thanks Bruno - still not working for me for some reason. Did you update the
extension in the chrome store? It looks like the latest version came last
December. Check out my settings below to make sure:

[image: Inline image 1]

[image: Inline image 2]

**Comment by Ceilican** [comment]
I did upload the new version, but (quite unusually) it took more than 24 hours for the new version to be published by Google in the Chrome Web Store. If you have a look again, you will see version 2.0.2 available there now.

The images of your last message are not being displayed.

**Comment by jfmasciocco** [comment]
Bruno!!! Thank you my friend, it's working. Really appreciate it!

Joe
