### ISSUE TITLE
Personal dictionary feature(Enhancement)

### ISSUE THREAD

**Issue by srikar0896** [OiWorld/MindTheWord#105]
Hello @Ceilican,
         As i mentioned in the proposal iam working on adding cross browser compatible and adding to dictionary in firefox feature to mindtheword extension in firefox .please visit the [link](https://github.com/srikar0896/Add-To-Dictionary/blob/master/README.md).and comment for any changes that would be useful to me.Thank you.

**Comment by ankit-m** [comment]
@srikar0896 isn't this already implemented in #89 ? Looks similar.

**Comment by srikar0896** [comment]
Oh thanks! @ankit-m can you specify where the code is for adding to dictionary.
