### ISSUE TITLE
Validation on Yandex Key

### ISSUE THREAD

**Issue by sjoanes** [OiWorld/MindTheWord#106]
**Problem:**
When you double click the text in the Yandex page you get "<key> Block Key". I and possibly many other people are pasting that into the input box without removing the "Block Key" part. Fails in the background page.

**Solution:**
Show warning if the string contains "Block Key" on saveYandexKey

Good tool, hate to see it not work because of something so silly.

**Comment by Ceilican** [comment]
You are right! Thanks for the idea!

**Comment by Ceilican** [comment]
Related issue: #111

**Comment by Ceilican** [comment]
This issue has been solved in the merged pull requests.
