### ISSUE TITLE
Blank tab heading

### ISSUE THREAD

**Issue by ankit-m** [OiWorld/MindTheWord#109]
The extension is not working and the options page headings are blank. I reset my master with upstream, but the problem persists. 

![err_blank](https://cloud.githubusercontent.com/assets/9019878/14940999/af76bf32-0faa-11e6-8999-4cd74e0aab07.png)

The issue was resolved only when I removed the extension and reinstalled it from my local repository. I haven't looked into the issue properly but I believe the issue is with `storage.get`. Background page shows the following error.

![storage_err](https://cloud.githubusercontent.com/assets/9019878/14941044/e178fc42-0fab-11e6-9a5c-7d9032e53fd1.png)

**Comment by Ceilican** [comment]
I wasn't able to reproduce this error here. I'm using Chrome Version 50.0.2661.94 (64-bit) for Mac.

**Comment by Ceilican** [comment]
Today I uploaded a new version to the Chrome Web Store, but it hasn't appeared yet.
