### ISSUE TITLE
Numbers should not be translated

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/MindTheWord#11]
Jan. 23 is translated incorrectly.

![screen shot 2013-12-07 at 7 50 28](https://f.cloud.github.com/assets/1809436/1698094/653e15a0-5f26-11e3-864e-20bd2975d1ae.png)

**Comment by Ceilican** [comment]
Perhaps this issue is partially fixed by now. But this needs to be checked.

**Comment by srikar0896** [comment]
hello ceilican,
I want to resolve this bug.where can i find the repository of this?

**Comment by Ceilican** [comment]
@srikar0896 Mind The Word's source code is here: https://github.com/OiWorld/MindTheWord

**Comment by srikar0896** [comment]
hey ceilican;
I've made the translate function just skip when it finds the number not to translate it.here's the link-https://github.com/OiWorld/MindTheWord/compare/master...srikar0896:patch-1

**Comment by Ceilican** [comment]
Thank you, @srikar0896 !  That's a fine and simple solution. I like it! Could you please create a pull request?

**Comment by srikar0896** [comment]
Thank you.sure
