### ISSUE TITLE
Localize Messages

### ISSUE THREAD

**Issue by ceilican** [OiWorld/MindTheWord#113]
As suggested by @omesh : https://github.com/OiWorld/MindTheWord/pull/108/files/581183847e4989ede7c1b57d2a7ac1b0eb0c7f50#r61735295

This is harder than it might seem. A way to do that can be seen here: https://github.com/OiWorld/CarbonFootprintGoogleMaps

**Comment by ankit-m** [comment]
I don't follow. Which messages are we trying to localize? 
@omesh can you please explain?

**Comment by Ceilican** [comment]
Well, now that message doesn't appear anymore. But the idea would be to localize all sentences seen by the user (e.g. in the options page, in the context menus, and so on).

**Comment by rohankatyal29** [comment]
All the messages/text in the extension should‪ be localised.

For eg: if a user opens the application from France all the labels in
options page should be in French

On Tuesday 3 May 2016, Ankit Muchhala <notifications@github.com> wrote:

> I don't follow. Which messages are we trying to localize?
> @omesh <https://github.com/omesh> can you please explain?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/OiWorld/MindTheWord/issues/113#issuecomment-216464650>
>


-- 
Regards,
Rohan Katyal

Please ignore the typos and brevity, email sent using a small form factor
device

**Comment by ankit-m** [comment]
Thanks @Ceilican @rohankatyal29
