### ISSUE TITLE
User-defined translations are not working properly

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/MindTheWord#12]
"a":"a" is working, but "the":"the" is not...

![screen shot 2013-12-07 at 8 26 13](https://f.cloud.github.com/assets/1809436/1698111/2806cf3e-5f2a-11e3-9164-ef0cb6081d1c.png)

**Comment by rohankatyal29** [comment]
As I mentioned in #69, translations such **the:the and a:a** will be filtered out. 
<img width="649" alt="screen shot 2016-03-07 at 11 42 02 am" src="https://cloud.githubusercontent.com/assets/2452426/13562125/b5af6690-e45a-11e5-92ad-9ae415fab252.png">

**Comment by ankit-m** [comment]
@Ceilican I think this issue is resolved. We should close this as well.

**Comment by Ceilican** [comment]
Indeed. I missed it.
