### ISSUE TITLE
Easily add new words to the user-defined translations

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/MindTheWord#14]
A user gave the following interesting feedback:

> hey there awesome program i am using it to help me learn spanish, it would be very cool if you could make it always translate the same 10 word s or something then when you know each word you could right click on word and select learnt or somehting like that and then it adds another word to the list, that would be sick! I understand you can do this manually in the settings but if it could be automatic would be so good. thanks for making it :-)

**Comment by rohankatyal29** [comment]
How can we get the initial 10 words without having the user to enter them?

**Comment by Ceilican** [comment]
He wants an easy way to add new words to the user-defined dictionary. I think @Stormteller has started working on this. The number "10" there was just an arbitrary number. To understand what he means, replace "the same 10 words or something" by "the same list of words (i.e. the user defined translations).
