### ISSUE TITLE
URI Too Long for Yandex

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/MindTheWord#163]
I experienced the following error:

<img width="1276" alt="screen shot 2016-07-23 at 17 28 06" src="https://cloud.githubusercontent.com/assets/1809436/17076632/fb263d0e-50fa-11e6-8fad-8aef59a6bd4c.png">

MTW used to have a function that broke down long URL requests to Google Translate into smaller requests. We should do something similar for Yandex too.

**Comment by ankit-m** [comment]
Oh! This is the first time I have seen this error. We still have that function in Google Translate. I think we will need to implement the same thing here.

**Comment by Ceilican** [comment]
@ankit-m , are you working on this issue now? @rohankatyal29 told me that you are.  Do you know how long it will take to solve it? @rohankatyal29 and I think this issue is affecting Monica, who will present MTW to many potential new users soon.

**Comment by ankit-m** [comment]
@Ceilican I am working on it. I will raise a PR by tonight.
