### ISSUE TITLE
Make it easy to blacklist current site

### ISSUE THREAD

**Issue by masukomi** [OiWorld/MindTheWord#17]
there are many reasons you'd want to blacklist the current site, but frankly, it's a pain. There should be an easy way to blacklist it. 

I think the best way is probably to add a right-click menu item for Mind The Word that has a sub-menu item of "Blacklist Current Page" which blacklists the current page. I believe that [this is the documentation for adding such functionality](https://developer.chrome.com/extensions/contextMenus).

Later on other functionality can be aded to the sub-menu like "Don't translate selected word(s)" or "Process this page"

**Comment by Ceilican** [comment]
@masukomi Could you have a look on the newest version of Mind The Word and tell us if you like the blacklisting feature? We would greatly appreciate your feedback!
