### ISSUE TITLE
Dropdown width is varying

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/MindTheWord#172]
The dropdown selectors should have fixed width. Right not, their width varies depending on which translator is chosen:

<img width="916" alt="screen shot 2016-07-24 at 20 29 06" src="https://cloud.githubusercontent.com/assets/1809436/17083267/782326cc-51dd-11e6-827f-0a0517194dd9.png">
<img width="902" alt="screen shot 2016-07-24 at 20 29 22" src="https://cloud.githubusercontent.com/assets/1809436/17083268/7827fd0a-51dd-11e6-862f-38542d386385.png">

**Comment by ankit-m** [comment]
@Ceilican that is because the languages change with different translators. Do you want me to fix the widths to the maximum?

**Comment by Ceilican** [comment]
I think fixing the width to the maximum would be a good idea.

**Comment by Ceilican** [comment]
But this other issue (https://github.com/OiWorld/MindTheWord/issues/173) is more urgent.
