### ISSUE TITLE
When a new pattern is created, the new pattern should be automatically selected

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/MindTheWord#173]
It is not intuitive for the user that he has to select the pattern he has just created, especially when it is the first pattern.

**Comment by Ceilican** [comment]
@ankit-m , could you look at this as soon as possible?

**Comment by Ceilican** [comment]
I would like to release a new version for Monica still tonight. Do you think you can solve this issue now?

**Comment by ankit-m** [comment]
Absolutely! Will get this done ASAP.

**Comment by ankit-m** [comment]
@Ceilican this issue is resolved.
