### ISSUE TITLE
Social Media icons in options page should not be underlined when mouse hovers

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/MindTheWord#178]

**Comment by ankit-m** [comment]
@Ceilican issue resolved.

**Comment by Ceilican** [comment]
I thought merging the PR would close issue automatically. But I think it didn't because the PR's description was not written in automatically understandable form. Next time, try to write "Closes #172 . Closes #177 . Closes #178 ." instead of "closes #172 #177 #178".
