### ISSUE TITLE
Breaking user defined translations

### ISSUE THREAD

**Issue by ankit-m** [OiWorld/MindTheWord#184]
The user defined translations are no longer working

![oneerror](https://cloud.githubusercontent.com/assets/9019878/17258574/34b0ad04-55e5-11e6-98d0-3d87a07b4e9a.png)

The following lines are generating the error. @rohankatyal29 you just need to handle these cases.
```javascript
this.stats['translatorWiseWordCount'][0][currentMonth][this.translator][0] += numberOfTranslatedWords;
this.stats['translatorWiseWordCount'][0][currentMonth][this.translator][1] += numberOfTranslatedCharacters;
this.stats['translatorWiseWordCount'][0][currentMonth][this.translator][2] += numberOfTranslatedCharacters;
this.stats['translatorWiseWordCount'][1][currentDay][this.translator][0] += numberOfTranslatedWords;
this.stats['translatorWiseWordCount'][1][currentDay][this.translator][1] += numberOfTranslatedCharacters;
this.stats['translatorWiseWordCount'][1][currentDay][this.translator][2] += numberOfTranslatedCharacters;
```

**Comment by rohankatyal29** [comment]
I don't understand how are these lines can cause the user defined translations to break?

**Comment by rohankatyal29** [comment]
If you remove the previous version of the extension and then add the new one, this error should disappear. If you only refresh the rebased code, the local storage won't be refreshed.
