### ISSUE TITLE
Blacklisted words are getting translated

### ISSUE THREAD

**Issue by rohankatyal29** [OiWorld/MindTheWord#188]

**Comment by ankit-m** [comment]
@rohankatyal29 can you please point me to the website and your configuration?

**Comment by ankit-m** [comment]
@rohankatyal29 I cannot reproduce the issue on the link you said with the config. I also tried on the wikipedia page of `You`, still I cannot find the word `vous` - french for you.

**Comment by sudeepb02** [comment]
@ankit-m  Agreed 👍 . I even tried on some other websites, but I think it is working fine @rohankatyal29
