### ISSUE TITLE
Dropdown for "Voice Name" does not fit in the "Playback Settings" box

### ISSUE THREAD

**Issue by ceilican** [OiWorld/MindTheWord#197]
<img width="516" alt="screen shot 2016-09-22 at 21 51 36" src="https://cloud.githubusercontent.com/assets/1809436/18770679/e92565dc-810e-11e6-81ea-997d1f85e187.png">

**Comment by Ceilican** [comment]
@rohankatyal29 , could you fix this?

**Comment by boro741** [comment]
fixed the issue https://github.com/OiWorld/MindTheWord/pull/200

**Comment by ceilican** [comment]
Thanks!
