### ISSUE TITLE
It appears as MindTheWord is not working on some Australian news sites

### ISSUE THREAD

**Issue by ceilican** [OiWorld/MindTheWord#199]
The following sites were reported by a user:

* news.com.au 
* theherald.com.au
* nhs.trade

I have verified that it is not working on "news.com.au".

**Comment by ceilican** [comment]
I have just checked and it is actually working in the other two sites. So, only news.com.au is not working.

**Comment by rahulchawla1995** [comment]
@ceilican does this issue require a contributor,i am a newcomer and would very much like to help if possible

**Comment by ceilican** [comment]
Hi @rahulchawla1995 ! Yes, it would be great if you could have a look on this issue and try to understand why MindTheWord is not working on news.com.au.

**Comment by ceilican** [comment]
Maybe this issue is due to dynamically loading of content.

**Comment by rahulchawla1995** [comment]
@ceilican -i ll have a look into it
