### ISSUE TITLE
Error: (SystemJS) XHR error on Linux

### ISSUE THREAD

**Issue by sudeepb02** [OiWorld/MindTheWord#210]
Running `npm test` on my Linux system gives me the following error : 

> 5 03 2017 15:56:59.390:WARN [web-server]: 404: /base/jspm_packages/system-polyfills.js
05 03 2017 15:56:59.789:WARN [web-server]: 404: /base/jspm_packages/npm/lodash@4.14.0.js
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  Error: (SystemJS) XHR error (404 Not Found) loading http://localhost:9000/jspm_packages/npm/lodash@4.14.0.js
  	Error loading http://localhost:9000/jspm_packages/npm/lodash@4.14.0.js as "lodash" from http://localhost:9000/lib/scripts/mtw.js
PhantomJS
2.1.1 (Linux 0.0.0): Executed 0 of 0 ERROR (0.74 secs / 0 secs)
npm ERR! Test failed.  See above for more details.

**Comment by ceilican** [comment]
Are you still experiencing this issue?
Is your Linux system standard? Do you have any firewall that could be preventing access to localhost:9000 ?

**Comment by ceilican** [comment]
Anyone else using linux can reproduce the issue described above? (I'm using Mac, so I can't.)

**Comment by ceilican** [comment]
@sudeepb02 We are moving to gitlab. So please use our new repository and issue tracker at http://www.gitlab.com/aossie . Have a look on http://www.aossie.org as well...

**Comment by boro741** [comment]
I'm able to reproduce the same error on my linux on virtual box.
![npm erro](https://cloud.githubusercontent.com/assets/16509376/23643157/e5c97862-0325-11e7-80b3-71ee859f48fe.png)

**Comment by boro741** [comment]
This error can be resoled by running commands that are on the [CONTRIBUTE.md](https://github.com/OiWorld/MindTheWord/blob/master/CONTRIBUTE.md) 
`npm install -g jspm gulp gulp-cli jsdoc karma-cli`
`npm install`
`jspm install`

Here's the error I was able to reproduce: 
![npm erro](https://cloud.githubusercontent.com/assets/16509376/23643268/aab24154-0326-11e7-82c6-6e6184206a82.png)

Resolved the issue: 
![res](https://cloud.githubusercontent.com/assets/16509376/23643254/91aa5476-0326-11e7-956a-3836df9a13a9.png)

**Comment by ceilican** [comment]
Could you please improve the README.md and the CONTRIBUTE.md, so that future users/develoeprs do not face the same issue? Please submit a pull request to our gitlab repository: www.gitlab.com/aossie/MindTheWord/

**Comment by boro741** [comment]
@ceilican  sure.

**Comment by sudeepb02** [comment]
@boro741 Are you working on improving the README? Let me know in case you're not so I'll submit a PR

**Comment by sudeepb02** [comment]
Another solution would be to initialize the SystemJS using 
`jspm dl-loader`

**Comment by boro741** [comment]
@sudeepb02 yea I'm working on improving the README.md file.

**Comment by ceilican** [comment]
@sudeepb02 
> Another solution would be to initialize the SystemJS using
> jspm dl-loader

This would be an alternative to what, exactly?

Anyway, if this would make it easier for people to contribute to the project, it is certainly welcome.

**Comment by sudeepb02** [comment]
@ceilican Alternative solution to the above problem

**Comment by ceilican** [comment]
@sudeepb02  if you would like to describe this alternative solution in the README as well, please go ahead. Just wait for @boro741 's merge request to be merged first. (You can see his MR in our gitlab repository.)
