### ISSUE TITLE
Improve Javascript style

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/MindTheWord#35]
The current code does not adhere to typical Javascript style conventions. The code should be improved according to Google's Javascript Style Guide (e.g. https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml) or other well-know style guide.

The code should also be properly commented, also according to style guides.

**Comment by suhasdarsi** [comment]
I would like to work on this

**Comment by goelrohan6** [comment]
Is the issue still open? as you have already merged it.

**Comment by Ceilican** [comment]
@goelrohan6 , The merged pull request https://github.com/OiWorld/MindTheWord/pull/60 (by @rohankatyal29) already does the most important improvements. However, [Google's Javascript Style Guide](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml) gives many other recommendations that could still be done. Therefore, I leave this issue still open for now.

Nevertheless, anyone interested in doing working on this issue should coordinate with others already working on this. It's ok to have many people working on the same issue, but you should try not to do exactly the same thing. In this spirit, I propose that whoever wants to continue working on this issue should first declare here on which aspect of the [Style Guide](https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml) you will work on.

Thank you all!

**Comment by lucky4287** [comment]
How can i get the code to make changes in it?

**Comment by rohankatyal29** [comment]
You can fork this repository and then clone it on your machine

**Comment by lucky4287** [comment]
i want to upload the updated code. How to do it?

**Comment by Ceilican** [comment]
@lucky4287 There are many tutorials explaining how to use git and github. Just google for it and try to learn how to "commit", "push", "pull" and make a "pull request".

**Comment by ankit-m** [comment]
@rohankatyal29 @Ceilican There are a lot of style changes, especially in commenting and curly braces. These changes are span across various files. Should I make changes in all the files and make a single commit? Or different commits for different files?

**Comment by rohankatyal29** [comment]
@ankit-m , you should make a single commit
