### ISSUE TITLE
Create button doesn't create new configurations, and user cannot change from the default latin translation

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/MindTheWord#39]
A few users have reported the following issue:

> Unfortunately, whenever I try to create a new translation configuration in "Mind the Word" nothing seems to happen, and Chrome just continues to translate things into Latin. Pressing the "Create" button doesn't appear to be doing anything. Any help would be greatly appreciated.

I have been unable to reproduce this on my own computer. Therefore I do not know what is going on.

**Comment by RyanRusnak** [comment]
It looks like the create button is throwing a JS error:

```
Uncaught SyntaxError: Unexpected token u
createPattern	@	options.js:181
```

savedPatterns is undefined and I think that is causing the error. I think every new user will have no saved patters though. I tried adding one and still experienced the error so maybe they are not being persisted.

**Comment by Ceilican** [comment]
Hi Ryan! Thanks for the information. I am still not able to reproduce the error in my computer. Therefore, I rely on people like you, who can provide more information about the error. I agree with you that this bug must be due to a persistence error, but I wonder why it is happening only to a few users. Do you have any idea?

**Comment by RyanRusnak** [comment]
You are right. Locally, the plugin works perfectly. However, installing from the chrome store causes an error. See attached screenshots for each:
<img width="1317" alt="screen shot 2015-09-11 at 11 07 14 am" src="https://cloud.githubusercontent.com/assets/952698/9859933/e844f856-5add-11e5-9dc8-83a0763f2564.png">
<img width="1327" alt="screen shot 2015-09-11 at 11 10 19 am" src="https://cloud.githubusercontent.com/assets/952698/9859932/e8447bc4-5add-11e5-9a9e-cdb70fa0ea96.png">

**Comment by Stormteller** [comment]
I got this error, when I had tried to turn app on, before I visited options page after installation (I installed it locally). But after I had created config and opened page, nothing have changed, no one word was highlighted.

**Comment by ankit-m** [comment]
There was a null case error (S('savedPatterns') was referencing to undefined) in createPattern function. As a result new configurations could not be created. I have fixed this issue and also added duplicate configuration handling. #65

**Comment by rohankatyal29** [comment]
@ankit-m : How did you reproduce this issue?

**Comment by Ceilican** [comment]
It is still puzzling that S('savedPatterns') ever references to "undefined". This should never happen.  Pull request https://github.com/OiWorld/MindTheWord/pull/65 is good, because it makes the extension more resistant to such "undefined" cases, but we still don't know why it is "undefined" sometimes (and only for a few users).

**Comment by ankit-m** [comment]
@Ceilican this occurs during cold start. When a user first installs the extension, only then they get this error. The `savedPatterns` variable is undefined in the first go, which causes an exception. 

Here is the original error in the extension downloaded from webstore. 
![error](https://cloud.githubusercontent.com/assets/9019878/13566679/ab8d338c-e47c-11e5-9771-eac5ec029e7b.png)

The problem is with this snippet

```javascript
  if (data == null || JSON.stringify(data) == '{}') { // in this case, storage was not initialized yet
        console.log('setting storage to defaultStorage (stringified): ');
        console.log(JSON.stringify(defaultStorage));
        storage.set(defaultStorage);
        d = defaultStorage;
```
**`data` is NOT null NEITHER `{}`** because it has `activation: true`. As a result `d` is not set to `defaultStorage`. So if someone downloads, and turns on, defaultStorage is never set. This is causing variables to be undefined. I will solve this and raise a pull request.

**Comment by Ceilican** [comment]
But why does this happen only to some users?

**Comment by ankit-m** [comment]
Because only some people turn on right after installation, before going to options page which sets the `activation` field in `data` object.

**Comment by Ceilican** [comment]
Yes, please go ahead!
