### ISSUE TITLE
Add option to limit translations to user specified only

### ISSUE THREAD

**Issue by chris838** [OiWorld/MindTheWord#47]
I'd rather ditch support of Google Translate and Yamdex and translate only based on the user specified list.

**Comment by chris838** [comment]
Alternatively - instead of specifying a translation dictionary (which is a crude 1-1 translation mapping that often gives weird results) it would be nice to specify a set of *words or phrases that am learning* in the target language. Ideally the extension would then only target words that translate to elements in this set, ensuring that I'm only presented with words that I'm actually interested in learning.

**Comment by Ceilican** [comment]
> I'd rather ditch support of Google Translate and Yamdex and translate only based on the user specified list.

I suspect most users would not be patient to create their own translation lists...

> Alternatively - instead of specifying a translation dictionary (which is a crude 1-1 translation mapping that often gives weird results) it would be nice to specify a set of words or phrases that am learning in the target language. Ideally the extension would then only target words that translate to elements in this set, ensuring that I'm only presented with words that I'm actually interested in learning.

That's a good idea. I will keep it in mind, but I can't promise to implement it soon, because I'm short of time right now. In case you know how to program in Javascript (or if you have friends who do) and would like to volunteer to implement this feature, let me know.

**Comment by chris838** [comment]
I've added a switch to limit translations to only those in the user specified list, check out my fork if you are interested. I also added some unit testing that you might find useful (I found it easier to dev outside of Chrome).
Closing this issue for now.

**Comment by Ceilican** [comment]
Thanks! Your unit tests are great, by the way.

I would like to pull your fork. Are you still working on anything else? If yes, I will wait for you to finish. When you have finished everything you are currently working on, please make a pull request.

**Comment by chris838** [comment]
Awesome, thanks!
Just got one more bug fix then I'll submit a PR.

**Comment by chris838** [comment]
https://github.com/OiWorld/MindTheWord/pull/50
