### ISSUE TITLE
Only randomly translate user-defined words

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/MindTheWord#52]
Mark requested:

> Can you please a a function that i can give the app a word list 
and only this words will be translated.

 > Wound be useful if i learn a new language and i only want you app to trans 
 the most 100 most important words. But the words should not always translate 
so a random funcion here would very good. Otherwise it would be frustrating 
and to difficult to unterstand.

**Comment by rohankatyal29** [comment]
Isn't this feature already there? 

<img width="1116" alt="screen shot 2016-03-06 at 7 56 58 pm" src="https://cloud.githubusercontent.com/assets/2452426/13554718/a4186d30-e3d5-11e5-91f2-3cd97697f560.png">

**Comment by Ceilican** [comment]
No, not yet. Right now, MTW uses the user-defined translations **additionally** to the random translations obtained through Yandex or Google Translate.  This user asked for the ability to use **only** the user-defined translations.

**Comment by rohankatyal29** [comment]
I selected the following translation configuration (without limiting to user-defined translations only)
<img width="1076" alt="screen shot 2016-03-08 at 12 42 20 pm" src="https://cloud.githubusercontent.com/assets/2452426/13594556/4e035cc8-e52b-11e5-846b-0ada89e1fa4d.png">

and this was the output 
<img width="741" alt="screen shot 2016-03-08 at 12 41 47 pm" src="https://cloud.githubusercontent.com/assets/2452426/13594575/6c1757c8-e52b-11e5-955c-d3a58ec6987b.png">

After defining the user translations and checking the limit user translations checkbox 
<img width="703" alt="screen shot 2016-03-08 at 12 42 15 pm" src="https://cloud.githubusercontent.com/assets/2452426/13594583/74ca7c24-e52b-11e5-8a49-635b505ffe03.png">

the output became this
<img width="813" alt="screen shot 2016-03-08 at 12 42 04 pm" src="https://cloud.githubusercontent.com/assets/2452426/13594600/8bf94bf0-e52b-11e5-8c4b-2661aee828c2.png">

I don't think the user defined translations are in addition to the random translations. 
Am I missing something?

**Comment by Ceilican** [comment]
Oh, yes. I forgot about that checkbox. It is a recent addition, and my previous comment referred to a version where this checkbox did not exist.
