### ISSUE TITLE
Failure to inject CSS

### ISSUE THREAD

**Issue by Ceilican** [OiWorld/MindTheWord#56]
Reported by Ryan:

![image001](https://cloud.githubusercontent.com/assets/1809436/11761284/50e73f2c-a110-11e5-9ebb-4df4aac971ea.png)

**Comment by Ceilican** [comment]
So far, this has been observed only in: http://www.linustechtips.com/

**Comment by ankit-m** [comment]
@Ceilican I can't seem to reproduce this error on the website. 

![linus](https://cloud.githubusercontent.com/assets/9019878/13805612/1ce2abe2-eb7c-11e5-99df-ce3585bb5769.png)

**Comment by Ceilican** [comment]
Thanks for checking this. Probably something changed in the website, and the problem was solved on their side. I will close the issue. Thanks!
