### ISSUE TITLE
Translation is not working

### ISSUE THREAD

**Issue by jinankjain** [OiWorld/MindTheWord#64]
I was trying to use the chrome extension by setting language to translate from Chinese to English using Google Translate but I was unable to see any results.

Could someone help me out?

**Comment by rohankatyal29** [comment]
@jinankjain: Hi, can you post some screenshots and logs?

**Comment by Ceilican** [comment]
Make sure you added your Yandex key.

If it still doesn't work for you, please follow the [troubleshooting instructions](https://github.com/OiWorld/MindTheWord/blob/master/Troubleshooting/Troubleshooting.md).

I'm closing this issue for now.
