### ISSUE TITLE
Same translation configuration from different providers is not allowed

### ISSUE THREAD

**Issue by marksurnin** [OiWorld/MindTheWord#90]
For example, when there is a translation configuration "Use **Google** to translate 15% of all content from English to Spanish", the options page does not let me to set up a configuration "Use **Yandex** to translate 15% of all content from English to Spanish", as seen on the screenshots below.

Right before clicking the Create button:

<img width="1015" alt="screen shot 2016-03-11 at 3 53 13 pm" src="https://cloud.githubusercontent.com/assets/5126685/13706048/c23661ec-e7a3-11e5-9017-7fdf49466cdc.png">

And after:

<img width="1007" alt="screen shot 2016-03-11 at 3 53 17 pm" src="https://cloud.githubusercontent.com/assets/5126685/13706052/c84d723c-e7a3-11e5-9c03-9a950006bfda.png">

While there are some problems with the Google Translate API and users are advised to use Yandex, I suggest allowing them to have the exact same translation configuration, given that the providers are different.

**Comment by Ceilican** [comment]
You are right!
