### ISSUE TITLE
error in setting Yandex languages 

### ISSUE THREAD

**Issue by srikar0896** [OiWorld/MindTheWord#93]
![screenshot 61](https://cloud.githubusercontent.com/assets/17567875/13733514/d1006e4e-e9b9-11e5-97ce-1e8383fff752.png)

error in setting yandex languages.Unable to select the target language and the src language is set english and unable to change it.

**Comment by ankit-m** [comment]
@srikar0896 have you merged with upstream?

**Comment by srikar0896** [comment]
@ankit-m no

**Comment by ankit-m** [comment]
This issue has been resolved. Merge with upstream and it will work.
