### ISSUE TITLE
Handling dynamically loaded content

### ISSUE THREAD

**Issue by alexklibisz** [OiWorld/MindTheWord#95]
If I'm not mistaken, there is currently no support for dynamically loaded page content. And by extension, there would be no support for JS-only single page apps.

For example, when you open a page on reddit, all of the server-loaded content is made available for translation and the translations are done correctly. However, when you click "load more comments" and load more comments into the DOM, the new comments are never translated. The same can be said for Twitter and Facebook feeds.

@Ceilican Am I missing something? Are there any plans/strategy to address this? I'd be glad to look into resolving it.

**Comment by rohankatyal29** [comment]
A simple MutationObserver will do the job, no?

**Comment by alexklibisz** [comment]
@rohankatyal29 I've never used the MutationObserver but from looking at the spec on MDN, I would say that this is the option to try first. However I'm wondering how (or if it's worth it) to determine the specific nodes that were changed or added. That way we don't recompute the entire page every time.

**Comment by ankit-m** [comment]
@alexklibisz For long pages, watching nodes for mutations, would affect the performance significantly. For each mutation, an API call will be made - again a bottleneck. 

Also, each page uses different tags to load data - some might use `p`, some might use `span`. Which nodes to watch will be a tough part to solve.

**Comment by alexklibisz** [comment]
@ankit-m Right. I'll do some research to see if anyone else has solved a similar problem and documented it.

**Comment by Ceilican** [comment]
> @Ceilican Am I missing something? Are there any plans/strategy to address this? I'd be glad to look into resolving it.

@alexklibisz You are right. And no, I haven't made any plans to address this issue (I always had more pressing issues to worry about). Thank you for looking at it.

@ankit-m @rohankatyal29 thank you for your suggestions too!

**Comment by Ceilican** [comment]
A user also reported that MTW is not working on some newspaper websites such as CNN and USA Today. I think it might be because of this bug.

**Comment by rohankatyal29** [comment]
@Ceilican, @ankit-m  - I am working on this

**Comment by alexklibisz** [comment]
This may already be solved, but here's a solution that's popped in my head since opening this issue way back in March:

On the first translation pass (when the page is loaded), apply a class `mtw-translated` to any element with text that was translated. Then use `setInterval()` to look for new text elements without the `mtw-translated` class every x milliseconds. Every time you translate an element containing text, just apply that `mtw-translated` class. So you're basically polling for pieces of text that you haven't already translated. Anything that you've already translated gets the `mtw-translated` class applied.

I'm not completely certain that will work as I haven't looked at the code for a while, but figured I would mention it as an option.

**Comment by Ceilican** [comment]
Thanks you for the suggestion, @alexklibisz !
